---
title: "PR3"
format: md
---

# Название

Основы обработки данных с помощью R и Dplyr

## Цель

1.  Развить практические навыки использования языка программирования R для обработки данных
2.  Закрепить знания базовых типов данных языка R
3.  Развить практические навыки использования функций обработки данных пакета dplyr – функции select(), filter(), mutate(), arrange(), group_by()

## Исходные данные

1.  Ноутбук
2.  Условие для практической работы

## Общий план выполнения

1.  Установить библиотеку nycflights13.
2.  Проанализировать встроенные в пакет nycflights13 наборы данных с помощью языка R и ответить на вопросы:
    1.  Сколько встроенных в пакет nycflights13 датафреймов?
    2.  Сколько строк в каждом датафрейме?
    3.  Сколько столбцов в каждом датафрейме?
    4.  Как просмотреть примерный вид датафрейма?
    5.  Сколько компаний-перевозчиков (carrier) учитывают эти наборы данных (представлено в наборах данных)?
    6.  Сколько рейсов принял аэропорт John F Kennedy Intl в мае?
    7.  Какой самый северный аэропорт?
    8.  Какой аэропорт самый высокогорный (находится выше всех над уровнем моря)?
    9.  Какие бортовые номера у самых старых самолетов?
    10. Какая средняя температура воздуха была в сентябре в аэропорту John F Kennedy Intl (в градусах Цельсия).
    11. Самолеты какой авиакомпании совершили больше всего вылетов в июне?
    12. Самолеты какой авиакомпании задерживались чаще других в 2013 году?
3.  Оформить отчет в соответствии с шаблоном
